No error handling for error returns in init_child



unit tests not converted to python3 and moved to old_unit_tests folder ... not sure what the original idea of these tests were.

mask.py tests not working

get_subset_mask test not working

coverage not checked.


